services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DATABASE=main
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432


  auth_service:
    container_name: auth_service
    build: ./auth_service
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/authservice
      - JWT_SECRET=dstu
      - GRPC_SERVER_PORT=50051
    ports:
      - 8000:8000

  user_service:
    container_name: user_service
    build: ./user_service
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/userservice
      - GRPC_AUTH_SERVICE_URL=auth_service:50051
      - JWT_SECRET=dstu
    ports:
      - 8001:8000